name = "NeTask Factory"
author = "NeTask Collective"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e96e108e8c1fd00044692aad7c0ba205ca0b9db2001a0cacfc696037341ad57"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
datapack-folder = "kubejs/data"
