name = "NeTask Factory"
author = "NeTask Collective"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0b8167d4cd633df05f0e46db09706637c9551608605d97fba4a26c9373deb7b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
datapack-folder = "kubejs/data"
