name = "NeTask Mechanic"
author = "NeTask Collective"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7db07976806be668063a5665759496a0535dedaf690c4f9ead3fd83e7be26f10"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
