name = "NeTask Mechanic"
author = "NeTask Collective"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4f113721c01fe1da461b5d486de875eb1938ca99e59fc92ab31196e4b8eef5b"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
