name = "NeTask Reborn+"
author = "NeTask Collective"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a7925d016c1726bdd4db32481bdc053a7afc321dbc703b9adda8ff0f2e5ad29"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
