name = "NeTask Reborn+"
author = "NeTask Collective"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a87c97c22d83f83df1eca7e0d3443357440d55f234b5c1a0658eba95f3d41e80"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
