name = "NeTask Reborn+"
author = "NeTask Collective"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2cacf2cfa8da2469328184aa52d670ca12c809d216398f9dcd5ce0301b18405"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
