name = "NeTask Reborn+"
author = "NeTask Collective"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45a270dc7fbd588540b7e7b947681b922b1a042fb0ea0be68d01a7a427ab3c44"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
