name = "NeTask Reborn+"
author = "NeTask Collective"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2bf98900623289a9472c69e6084f01031357c1368b4584a467a8e0eb777c83ff"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
