name = "NeTask Reborn+ (aka KAMAZCraft)"
author = "NeTask Collective"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17a8ceccac62cc72a645b3d7e4da5ec14b75282ac77e133667c553ff645b479d"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
